# Generated by Django 4.2.2 on 2023-06-16 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0002_vehiculo_imagen'),
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('nid', models.AutoField(max_length=8, primary_key=True, serialize=False, verbose_name='Id')),
                ('animal', models.CharField(max_length=100, verbose_name='Animal')),
                ('categoria', models.CharField(max_length=100, verbose_name='categoria')),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Precio')),
                ('visualizaciones', models.PositiveIntegerField(default=0, verbose_name='Visualizaciones')),
                ('descripcion', models.TextField(max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='vehiculo',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes', verbose_name='Imagen'),
        ),
    ]
