# Generated by Django 4.2.2 on 2023-06-16 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0003_animal_alter_vehiculo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='nid',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Id'),
        ),
    ]
