# Generated by Django 4.2.2 on 2023-06-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0008_alter_animal_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='visualizaciones',
            field=models.PositiveIntegerField(default='', verbose_name='Visualizaciones'),
        ),
        migrations.DeleteModel(
            name='Vehiculo',
        ),
    ]
